AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 120